version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    container_name: HRSpace_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5454:5432