# Generated by Django 5.0.2 on 2024-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_profession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillrecruiter',
            options={'ordering': ('name',), 'verbose_name': 'Навык рекрутера', 'verbose_name_plural': 'навыки рекрутера'},
        ),
        migrations.AlterField(
            model_name='profession',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
