# Generated by Django 5.0.2 on 2024-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_skillrecruiter_options_alter_profession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='softwareSkills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skill_software', to='inquiries.skill', verbose_name='Навыки'),
        ),
    ]
