# Generated by Django 5.0.2 on 2024-03-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_duty_profession_alter_skill_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='программа')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='skillrecruiter',
            options={'ordering': ('name',), 'verbose_name': 'Навык рекрутера', 'verbose_name_plural': 'Навыки рекрутера'},
        ),
        migrations.RemoveField(
            model_name='duty',
            name='profession',
        ),
        migrations.AddField(
            model_name='duty',
            name='prof_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='inquiries.professionarea', verbose_name='проф область'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conditions',
            name='contractType',
            field=models.TextField(choices=[('1', 'Трудовой договор'), ('2', 'Договор ГПХ с физ.лицом'), ('3', 'Договор ГПХ с ИП и самозанятым')], verbose_name='verbose_name=способ оформления'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='socialPackage',
            field=models.ManyToManyField(related_name='social_package', to='inquiries.socialpackage', verbose_name='социальный пакет'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='workFormat',
            field=models.TextField(choices=[('1', 'Полный день'), ('2', 'Гибридный формат'), ('3', 'Удаленная работа')], verbose_name='формат работы'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='workSchedule',
            field=models.TextField(choices=[('1', 'Пятидневная неделя'), ('2', 'Сменная работа'), ('3', 'Вахтовый метод')], verbose_name='график работы'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='name',
            field=models.CharField(max_length=256, verbose_name='обязанность'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='resumeFormat',
            field=models.TextField(choices=[('1', 'Резюме без предварительного собеседования'), ('2', 'Резюме кандидатов, с которыми проведено интервью (с комментариями)')], verbose_name='вид резюме'),
        ),
        migrations.AlterField(
            model_name='professionarea',
            name='name',
            field=models.CharField(max_length=256, verbose_name='профессиональная область'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='softwareSkills',
            field=models.ManyToManyField(blank=True, related_name='skill_software', to='inquiries.software', verbose_name='знание программ'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
