# Generated by Django 5.0.2 on 2024-03-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_software_alter_skillrecruiter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='contractType',
            field=models.TextField(choices=[('1', 'Трудовой договор'), ('2', 'Договор ГПХ с физ.лицом'), ('3', 'Договор ГПХ с ИП и самозанятым')], verbose_name='способ оформления'),
        ),
    ]
