# Generated by Django 5.0.2 on 2024-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_alter_conditions_contracttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='desiredEmployeeExitDate',
            field=models.DateField(verbose_name='дата выхода на работу'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='desiredFirstResumeDate',
            field=models.DateField(verbose_name='дата получения резюме'),
        ),
    ]
