# Generated by Django 5.0.2 on 2024-03-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_alter_partnership_desiredemployeeexitdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='prof_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_prof_area', to='inquiries.professionarea', verbose_name='проф область'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='inquiries.conditions', verbose_name='условия работы'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='inquiries.description', verbose_name='описание вакансии'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='partnership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='inquiries.partnership', verbose_name='условия сотрудничества'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='recruiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='inquiries.recruiter', verbose_name='требования к рекрутерам'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='prof_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_area', to='inquiries.professionarea', verbose_name='профессиональная область'),
        ),
    ]
